### ISSUE TITLE
Nouvelle fiche : Logiciel Revit vers Logiciel IFC Builder 2

### ISSUE THREAD

**Issue by Ibex35** [alexandregrignon/MC-GT07-IFCINT#4]
layout: default-toc
comments: true

titre: Export du logiciel A et Import du logiciel B
source_nom: Logiciel A
source_version: Version A

![15-02-2017 09-26-13](https://cloud.githubusercontent.com/assets/26057186/23858655/75689d88-0801-11e7-8d70-a6514f35153c.jpg)

source_editeur: Editeur A
destination_nom: Logiciel B
destination_version: Version B
destination_editeur: Editeur B
usage_metier: role A > role B

statut: brouillon/relecture/publiée
maj: date sous la forme JJ/MM/AAAA

## Prérequis

...

## Export IFC depuis Logiciel A

...

## Import IFC dans Logiciel B

...

## Autres ressources mises à disposition

...

**Comment by DUHEM-Progiscad** [comment]
je propose cette image
![capture2](https://cloud.githubusercontent.com/assets/26298583/23858843/1f10801c-0802-11e7-90bb-dbe8f523a691.JPG)
